// resource.h — CoD4Radiant resource IDs
// AUTO-GENERATED by Phase 0.4 from CoD4Radiant.exe resource table.
// Numeric values are from the binary and must not be changed.
// Symbolic names: GtkRadiant resource.h where matching, IDD_/IDC_ invented otherwise.

#pragma once
#ifndef KISAK_RADIANT
#error this file is only for Radiant!
#endif

// ── Frame / App IDs ───────────────────────────────────────────────────────────
// IDR_MAINFRAME: main frame menu=214, toolbar=104, accelerator=101, icon=111
#define IDR_MAINFRAME                                      128
#define IDI_RADIANT                                        111
// P5.5: the real CMainFrame menu + accelerator (extracted from the binary's
// resource table; the MENU template is reconstructed in radiant.rc from raw/MENU/214.bin
// and raw/ACCELERATOR/101.bin). Numeric IDs are the binary's.
#define IDR_MENU_QUAKE3                                    214
#define IDR_MAIN_ACCEL                                     101
// Main toolbar (the binary's CToolBar::LoadToolBar(152); RT_TOOLBAR + RT_BITMAP id 152,
// 52 buttons across a 832x16 4bpp strip).  Bitmap extracted from CoD4Radiant.exe → toolbar.bmp.
#define IDR_TOOLBAR152                                     152
// Entity-display-mode popup (OnShowEntities/HandlePopup loads MENU 160; extracted from
// CoD4Radiant.exe RT_MENU 160 — a single "Popup" of 6 entity show-state options).
#define IDR_ENTITYPOPUP160                                 160
// The other two HandlePopup targets (IDB CMainFrame::OnPopupRenderMethod 0x4263E0 → 0x7C,
// OnPopupSelection 0x4263F0 → 0x7D).  Templates in radiant.rc, extracted from the PE.
#define IDR_POPUP_RENDER_METH                              124
#define IDR_POPUP_SELECTION                                125
// Radiant-custom File-menu command IDs (the menu reuses MFC standard IDs for
// New/Open/Save/Undo/Redo — ID_FILE_NEW/OPEN/SAVE 0xE100/01/03, ID_EDIT_UNDO/REDO
// 0xE12B/2C from afxres.h — but defines its own for Save-As / Exit / Save-selected).
#define ID_FILE_SAVEAS_RAD                                 32952   // 0x80B8 "Save as..."
#define ID_FILE_EXIT_RAD                                   32951   // 0x80B7 "Exit"
#define ID_FILE_SAVE_SELECTED                              32845   // 0x804D "Save selected..."
// ── Dialogs ──────────────────────────────────────────────────────────────────
#define IDD_FIND_TEXTURE                                   105     
#define IDD_ENTITY                                         106     
#define IDD_FIND_BRUSH                                     110     
#define IDD_ARBITRARY_ROTATION                             112     
#define IDD_ARBITRARY_SIDES                                113     
#define IDD_ABOUT_COD2RADIANT                              114     
#define IDD_SURFACE_INSPECTOR                              116
// Surface Inspector (IDD 116 / CSurfaceDlg) control IDs — the binary's, verbatim from the
// PE resource table (raw dlg116 template) and the CSurfaceDlg message map / DoDataExchange /
// Select_SetTexture_2 GetDlgItem cluster (CoD4Radiant.exe: 0x4572d0/0x457950/0x4576f0/msgmap
// 0x6e2e58).  The auto-generated IDC_1195/IDC_SPIN2/… names above alias the same numbers but
// were de-duplicated across dialogs; these give the surface inspector its own clean names.
#define IDC_SURFACE_INSP_SAMPLE_SIZE                       1035    // sample-size edit
#define IDC_SURFACE_INSP_TEX_REP_X                         1089    // "Texture x:" (repeats-in) edit
#define IDC_SURFACE_INSP_TEX_REP_Y                         1142    // "Texture y:" (repeats-in) edit
#define IDC_SURFACE_INSP_HORZ_SHIFT_IN                     1195    // Horizontal shift edit
#define IDC_SURFACE_INSP_VERT_SHIFT_IN                     1196    // Vertical shift edit
#define IDC_SURFACE_INSP_HORZ_STRETCH                      1211    // Horizontal stretch edit
#define IDC_SURFACE_INSP_VERT_STRETCH                      1213    // Vertical stretch edit
#define IDC_SURFACE_INSP_ROTATE                            1217    // Rotate edit
#define IDC_SURFACE_INSP_CURR_TEX                          1245    // current texture name edit
#define IDC_SURFACE_INSP_HORZ_SHIFT_SPIN                   1248    // Horizontal shift spin (msctls_updown32)
#define IDC_SURFACE_INSP_VERT_SHIFT_SPIN                   1251    // Vertical shift spin
#define IDC_SURFACE_INSP_VERT_STRETCH_SPIN                 1254    // Vertical stretch spin
#define IDC_SURFACE_INSP_HORZ_STRETCH_SPIN                 1257    // Horizontal stretch spin
#define IDC_SURFACE_INSP_ROTATE_SPIN                       1259    // Rotate spin
#define IDC_SURFACE_INSP_SAMPLE_SIZE_SPIN                  1260    // sample-size spin
#define IDC_SURFACE_INSP_BTN_CAP                           1282    // "CAP" button
#define IDC_SURFACE_INSP_BTN_SET                           1283    // "Set..." button
#define IDC_SURFACE_INSP_BTN_NATURAL                       1284    // "Natural" button
#define IDC_SURFACE_INSP_BTN_FIT                           1286    // "Fit" button
#define IDC_SURFACE_INSP_BTN_LMAP                          1287    // "Lmap" button
#define IDC_SURFACE_INSP_TEX_REP_X_SPIN                    1453    // "Texture x:" spin
#define IDC_SURFACE_INSP_TEX_REP_Y_SPIN                    1455    // "Texture y:" spin
#define IDC_SURFACE_INSP_PATCH_2D                          1477    // radio "Terrain uses 2D distance"
#define IDC_SURFACE_INSP_PATCH_3D                          1478    // radio "Terrain uses 3d distance"
#define IDC_SURFACE_INSP_PATCH_CURVE                       1479    // radio "Terrain emulates curves"
#define IDC_SURFACE_INSP_TXT_REPEATS_X                     1560    // "Repeats in" X readout (static)
#define IDC_SURFACE_INSP_TXT_REPEATS_Y                     1562    // "Repeats in" Y readout (static)
#define IDC_SURFACE_INSP_BTN_DONE                          1489    // "Done" button (message map id)
#define IDC_SURFACE_INSP_BTN_CANCEL                        1198    // "Cancel" button (message map id)
#define IDD_COD4RADIANT_PREFERENCES                        127
// KISAK_RADIANT (P6): a minimal in-tree prefs dialog template. The binary's full
// CPrefsDlg template (127, dozens of controls) was never reconstructed into this .rc
// (only the menu + accelerators were), so this small template backs the working
// Edit->Preferences dialog with the load-bearing toggles. Full faithful 127 is parked.
#define IDD_RADIANT_PREFS_MINI                             5000
#define IDC_RAD_LIGHT_PREVIEW                              5001
#define IDC_RAD_SUN_PREVIEW                                5002
// Brush→Primitives sides dialog (IDD_ARBITRARY_SIDES=113 exists; its edit-control ID
// IDC_ARB_SIDES_IN was not reconstructed — invented here in the custom 5000+ range).
#define IDC_ARB_SIDES_IN                                   5003
// AdvPatchEditDlg (terrain-paint) — hand-built minimal template (binary IDD parked); its
// control IDs ARE the binary's (1424-1474) so the ported sub_401DB0/sub_43E6F0 GetDlgItem
// reads work.  The drives are g_curveEditCtrls (radii/strength) + the channel/mode reads.
#define IDD_ADVPATCHEDIT                                   5010
#define IDD_MAP_INFO                                       128
#define IDD_ENTITIES                                       129     
#define IDD_NEW_PROJECT                                    131     
#define IDD_MAPPED_COMMANDS                                132     
#define IDD_SCALE                                          145
// Help→Command list... (CCommandsDlg, IDB CommandlistDlg_Prolog 0x40B750 pushes 0x84).
#define IDD_DLG_COMMANDLIST                                132
#define IDD_FIND_REPLACE_TEXTURE_S                         147     
#define IDD_INFORMATION                                    150
#define IDC_INFO_TEXT                                      1136    // the IDD_INFORMATION message edit (PE template)
#define IDD_PROJECT_SETTINGS                               153     
#define IDD_DLG_154                                        154     
#define IDD_ADD_COMMAND                                    155     
#define IDD_PATCH_DENSITY                                  157     
#define IDD_PATCH_TEXTURE_LAYOUT                           159     
#define IDD_CAP                                            161     
#define IDD_THICKEN_PATCH                                  164     
#define IDD_PATCH_PROPERTIES                               172     
#define IDD_NEW                                            178     
#define IDD_DLG_180                                        180     
#define IDD_GO_TO_POSITION                                 184     
#define IDD_TERRAIN_DENSITY                                186     
#define IDD_ADVANCED_PATCH_EDITING_OPTIONS                 187     
#define IDD_SELECT_FROM_KEY_VALUE                          188     
#define IDD_SCRIPT_GROUP_NAME                              217     
#define IDD_EXPORT_TO_MAYA                                 224     
#define IDD_GVERTEX_COLOR_ALPHA_EDITING                    226     
#define IDD_VEHICLE_WINDOW                                 228     
#define IDD_MODEL_REPLACE                                  229     
#define IDD_LAYERS                                         230     
#define IDD_DLG_249                                        249     
#define IDD_DYNENTITY_WINDOW                               251     
// (dup diff val 178) #define IDD_NEW                                            30721
#define IDD_DLG_30722                                      30722   
#define IDD_DLG_30723                                      30723   
#define IDD_DLG_30734                                      30734   

// ── Dialog Controls ──────────────────────────────────────────────────────────
#define IDC_OK                                             1       // dlg105:"OK"; dlg110:"OK"; dlg112:"OK"
#define IDC_CANCEL                                         2       // dlg105:"Cancel"; dlg110:"Cancel"; dlg112:"Cancel"
#define IDC_APPLY                                          3       // dlg112:"Apply"; dlg172:"Apply"
#define IDC_ADD                                            4       // dlg217:"Add"
// (dup diff val 4) #define IDC_ADD                                            5       // dlg217:"Add"
#define IDC_REMOVE                                         6       // dlg217:"Remove"
// (dup diff val 6) #define IDC_REMOVE                                         7       // dlg217:"Remove"
#define IDC_AXIS                                           8       // dlg217:"AXIS"
// (dup diff val 4) #define IDC_ADD                                            9       // dlg217:"Add"
// (dup diff val 6) #define IDC_REMOVE                                         10      // dlg217:"Remove"
#define IDC_ALLIES                                         11      // dlg217:"ALLIES"
// (dup diff val 4) #define IDC_ADD                                            14      // dlg217:"Add"
// (dup diff val 6) #define IDC_REMOVE                                         15      // dlg217:"Remove"
#define IDC_100                                            100     // dlg30721:""
// (dup diff val 3) #define IDC_APPLY                                          121     // dlg147:"Apply"
#define IDC_LIVE_UPDATES_FROM_TEXTURE_CAMERA_WINDOWS       123     // dlg147:"Live updates from Texture/Camera Windows"
#define IDC_134                                            134     // dlg127:"#134"
#define IDC_137                                            137     // dlg127:"#136"
#define IDC_141                                            141     // dlg127:"#140"
#define IDC_142                                            142     // dlg127:"#142"
#define IDC_201                                            201     // dlg30722:""
#define IDC_202                                            202     // dlg30722:""
#define IDC_203                                            203     // dlg30722:""
#define IDC_204                                            204     // dlg30722:""
#define IDC_HIDE                                           1000    // dlg106:"Hide"
#define IDC_SPIN1                                          1001    // dlg112:"Spin1"
// (dup diff val 1001) #define IDC_SPIN1                                          1002    // dlg112:"Spin1"
#define IDC_1003                                           1003    // dlg127:"&2 button"
// (dup diff val 1001) #define IDC_SPIN1                                          1004    // dlg112:"Spin1"
#define IDC_1005                                           1005    // dlg127:"&3 button"
#define IDC_N                                              1006    // dlg127:"n"; dlg224:"Triangles"
#define IDC_1009                                           1009    // dlg127:""
#define IDC_1012                                           1012    // dlg127:""
#define IDC_1013                                           1013    // dlg128:""
#define IDC_1014                                           1014    // dlg127:""
#define IDC_LOAD_LAST_PROJECT_ON_OPEN                      1021    // dlg127:"Load last project on open"
#define IDC_TREE1                                          1022    // dlg129:"Tree1"
#define IDC_AUTO_SAVE_EVERY                                1023    // dlg127:"Auto save every "
#define IDC_LOAD_LAST_MAP_ON_OPEN                          1024    // dlg127:"Load last map on open"
#define IDC_LIST2                                          1025    // dlg129:"List2"
#define IDC_1026                                           1026    // dlg127:""
#define IDC_1027                                           1027    // dlg127:""
#define IDC_1029                                           1029    // dlg127:"..."
#define IDC_1033                                           1033    // dlg131:""; dlg172:""; dlg178:""
#define IDC_1035                                           1035    // dlg116:""
#define IDC_1036                                           1036    // dlg132:""
#define IDC_FACE_SELECTION                                 1040    // dlg127:"Face selection"
#define IDC_RIGHT_CLICK_TO_DROP_ENTITIES                   1042    // dlg127:"Right click to drop entities"
#define IDC_1044                                           1044    // dlg106:""
#define IDC_TEXTURE_SUBSET                                 1045    // dlg127:"Texture subset"; dlg224:"Merge"
#define IDC_1046                                           1046    // dlg106:""
#define IDC_TEXTURE_TOOLBAR                                1047    // dlg127:"Texture toolbar"
#define IDC_1048                                           1048    // dlg106:""; dlg180:"Reverse Filter"
#define IDC_1050                                           1050    // dlg106:""
#define IDC_SNAP_T_TO_GRID                                 1051    // dlg127:"Snap T to Grid"
#define IDC_1052                                           1052    // dlg106:""
#define IDC_TEXTURE_SCROLLBAR                              1054    // dlg127:"Texture scrollbar"
#define IDC_1055                                           1055    // dlg106:""
#define IDC_1057                                           1057    // dlg106:""
#define IDC_1059                                           1059    // dlg106:""
#define IDC_EASY                                           1061    // dlg106:"!Easy"
#define IDC_MEDIUM                                         1064    // dlg106:"!Medium"
#define IDC_1065                                           1065    // dlg127:""
#define IDC_HARD                                           1066    // dlg106:"!Hard"
#define IDC_DEATHMATCH                                     1068    // dlg106:"!DeathMatch"
#define IDC_INNER_RADIUS                                   1069    // dlg187:"&Inner Radius"
#define IDC_BUTTON1                                        1070    // dlg154:"Button1"; dlg187:"&Outer Radius"
#define IDC_AMPLITUDE                                      1071    // dlg187:"&Amplitude"
// (dup diff val 1001) #define IDC_SPIN1                                          1079    // dlg127:"Spin1"
#define IDC_PAINT_SIZING_INFO                              1084    // dlg127:"Paint sizing info"
#define IDC_LINKING_KEEPS_SELECTION                        1085    // dlg127:"Linking keeps selection"
#define IDC_1089                                           1089    // dlg116:""; dlg145:""; dlg159:""
// (dup diff val 1001) #define IDC_SPIN1                                          1091    // dlg127:"Spin1"
#define IDC_SNAPSHOTS                                      1094    // dlg127:"Snapshots"
#define IDC_LOSE_CHANGES                                   1095    // dlg127:"Lose changes?"
#define IDC_1097                                           1097    // dlg147:""
// (dup diff val 1001) #define IDC_SPIN1                                          1098    // dlg127:"Spin1"
#define IDC_1101                                           1101    // dlg147:""
#define IDC_1102                                           1102    // dlg172:""
#define IDC_REPLACE_WITHIN_SELECTED_BRUSHES_ONLY           1105    // dlg147:"Replace within selected brushes only"
#define IDC_1106                                           1106    // dlg172:""
#define IDC_FORCE_REPLACEMENT__IGNORE_CURRENT_TEXTUR       1109    // dlg147:"Force replacement (ignore current texture name)"
#define IDC_1136                                           1136    // dlg105:""; dlg150:""
#define IDC_1139                                           1139    // dlg112:""
#define IDC_1142                                           1142    // dlg116:""; dlg145:""; dlg159:""
#define IDC_1144                                           1144    // dlg112:""
#define IDC_1147                                           1147    // dlg145:""; dlg172:""
#define IDC_1148                                           1148    // dlg106:""
#define IDC_1151                                           1151    // dlg106:""
#define IDC_1153                                           1153    // dlg106:""
#define IDC_1156                                           1156    // dlg106:""
#define IDC_1158                                           1158    // dlg106:"135"
#define IDC_1160                                           1160    // dlg106:"180"
#define IDC_1162                                           1162    // dlg106:"225"
#define IDC_1164                                           1164    // dlg106:"270"
#define IDC_1166                                           1166    // dlg106:"90"
#define IDC_1168                                           1168    // dlg106:"45"
#define IDC_1170                                           1170    // dlg106:"360"
#define IDC_1172                                           1172    // dlg106:"315"
#define IDC_UP                                             1174    // dlg106:"Up"
#define IDC_DN                                             1176    // dlg106:"Dn"
#define IDC_DEL_KEY_PAIR                                   1182    // dlg106:"Del Key/Pair"
#define IDC_1186                                           1186    // dlg106:""
#define IDC_1195                                           1195    // dlg116:""; dlg154:""; dlg172:""
#define IDC_1196                                           1196    // dlg116:""; dlg154:""; dlg172:""
// (dup diff val 2) #define IDC_CANCEL                                         1198    // dlg116:"Cancel"
#define IDC_1201                                           1201    // dlg127:""
#define IDC_1204                                           1204    // dlg127:""
#define IDC_1208                                           1208    // dlg127:""
#define IDC_1211                                           1211    // dlg116:""; dlg154:""; dlg172:""
#define IDC_1213                                           1213    // dlg116:""; dlg154:""; dlg172:""
#define IDC_1217                                           1217    // dlg116:""; dlg154:""; dlg172:""
#define IDC_SLIDER1                                        1219    // dlg127:"Slider1"
#define IDC_UPDATE_XY_ON_DRAG                              1223    // dlg127:"Update XY on drag"
#define IDC_KEY                                            1224    // dlg106:"Key"
#define IDC_1225                                           1225    // dlg110:""
#define IDC_VALUE                                          1227    // dlg106:"Value"
#define IDC_1229                                           1229    // dlg106:""
#define IDC_1231                                           1231    // dlg110:""
#define IDC_1233                                           1233    // dlg113:""
#define IDC_1236                                           1236    // dlg112:""
#define IDC_1245                                           1245    // dlg116:""
#define IDC_ALT_ALWAYS_MOVE                                1246    // dlg127:"ALT always move"
#define IDC_SPIN2                                          1248    // dlg116:"Spin2"; dlg154:"Spin1"; dlg172:"Spin2"
#define IDC_MOUSE_CHASER                                   1249    // dlg127:"Mouse chaser"
// (dup diff val 1248) #define IDC_SPIN2                                          1251    // dlg116:"Spin2"; dlg154:"Spin1"; dlg172:"Spin2"
#define IDC_1253                                           1253    // dlg153:""
// (dup diff val 1248) #define IDC_SPIN2                                          1254    // dlg116:"Spin2"; dlg154:"Spin1"; dlg172:"Spin2"
#define IDC_DON_T_CLAMP_PLANE_POINTS                       1255    // dlg127:"Don't clamp plane points"
// (dup diff val 1248) #define IDC_SPIN2                                          1257    // dlg116:"Spin2"; dlg154:"Spin1"; dlg172:"Spin2"
// (dup diff val 1248) #define IDC_SPIN2                                          1259    // dlg116:"Spin2"; dlg154:"Spin1"; dlg172:"Spin2"
#define IDC_1260                                           1260    // dlg116:""; dlg153:""
#define IDC_1262                                           1262    // dlg154:""
#define IDC_1265                                           1265    // dlg153:""
#define IDC_1267                                           1267    // dlg155:""
#define IDC_1269                                           1269    // dlg155:""
#define IDC_1273                                           1273    // dlg153:""
#define IDC_1274                                           1274    // dlg153:""
#define IDC_1280                                           1280    // dlg157:""; dlg186:""
#define IDC_1281                                           1281    // dlg157:""; dlg186:""
#define IDC_CAP                                            1282    // dlg116:"CAP"; dlg172:"CAP"
#define IDC_SET                                            1283    // dlg116:"Set..."; dlg172:"Set..."
#define IDC_NATURAL                                        1284    // dlg116:"Natural"; dlg172:"Natural"
#define IDC_BEVEL                                          1285    // dlg161:"Bevel"
#define IDC_FIT                                            1286    // dlg116:"Fit"; dlg172:"Fit"
#define IDC_LMAP                                           1287    // dlg116:"Lmap"; dlg161:"Endcap"
#define IDC_SEAMS                                          1288    // dlg164:"Seams"
#define IDC_INVERTED_BEVEL                                 1289    // dlg161:"Inverted Bevel"
#define IDC_1290                                           1290    // dlg164:""
#define IDC_INVERTED_ENDCAP                                1291    // dlg161:"Inverted Endcap"
#define IDC_MODEL                                          1294    // dlg106:"Model..."
#define IDC_1298                                           1298    // dlg217:""
#define IDC_1300                                           1300    // dlg230:""
#define IDC_1301                                           1301    // dlg172:""
#define IDC_1302                                           1302    // dlg172:""
#define IDC_1303                                           1303    // dlg172:""
#define IDC_TAB1                                           1312    // dlg106:"Tab1"
#define IDC_ANGLES                                         1381    // dlg180:"Angles"
#define IDC_BLOCKS                                         1382    // dlg180:"Blocks"
#define IDC_NAMES                                          1387    // dlg180:"Names"
#define IDC_CONNECTIONS                                    1399    // dlg180:"Connections"
#define IDC_FILTER_SETTINGS_APPLY_TO_AREA_SELECTION        1411    // dlg180:"Filter Settings Apply to Area Selection"
#define IDC_COORDINATES                                    1416    // dlg180:"Coordinates"
#define IDC_1417                                           1417    // dlg184:""
#define IDC_ENTS_USE___COLOR__VALUE                        1420    // dlg127:"Ents use '_color' value"
#define IDC_TEXTURE_BRUSHES_IN_2D                          1423    // dlg127:"Texture brushes in 2d"
#define IDC_TEXTURE_MESHES_IN_2D                           1424    // dlg127:"Texture meshes in 2d"; dlg187:"Slider2"
#define IDC_SLIDER2                                        1425    // dlg187:"Slider2"
// (dup diff val 1425) #define IDC_SLIDER2                                        1426    // dlg187:"Slider2"
#define IDC_1428                                           1428    // dlg187:""
#define IDC_1429                                           1429    // dlg187:""
#define IDC_1430                                           1430    // dlg187:""
#define IDC_ONLY_PERFORM_SOFT_SELECTION_WHILE_THIS_D       1431    // dlg187:"Only perform soft selection while this dialog is open"
#define IDC_ALLOW_SOFT_SELECTION_ON_UNSELECTED_PATCH       1432    // dlg187:"Allow soft selection on unselected patches"; dlg188:""
#define IDC_1433                                           1433    // dlg188:""
#define IDC_KEY_SUBSTRING                                  1434    // dlg188:"Key Substring"
#define IDC_PAINT_HEIGHT                                   1435    // dlg187:"&Paint Height"; dlg188:"Value Substring"
#define IDC_SMOOTH                                         1436    // dlg187:"&Smooth"
#define IDC_FLATTEN                                        1437    // dlg187:"&Flatten"
#define IDC_NOISE                                          1438    // dlg187:"&Noise"
#define IDC_DRAG_UP___DOWN                                 1439    // dlg187:"&Drag Up / Down"
#define IDC_DISABLED                                       1440    // dlg187:"Disabled"
#define IDC_1441                                           1441    // dlg217:""
#define IDC_SCRIPT_HEALTH__ONE_OF_THESE_AI_WILL_DROP       1442    // dlg217:"script_health: One of these AI will drop a Health/Armor packet"
#define IDC_SCRIPT_KILLSPAWNER__DELETES_THE_SPAWNERS       1447    // dlg217:"script_killspawner: Deletes the spawners when the trigger is touched."
#define IDC_TERRAIN_USES_2D_DISTANCE__GOOD_FOR_GROUN       1449    // dlg159:"Terrain uses 2D distance (good for ground)"; dlg217:"AI using the first 
#define IDC_AI_USING_ANY_OF_THESE_TURRETS_WILL_MOVE_       1450    // dlg217:"AI using any of these turrets will move between turrets as necessary"
#define IDC_1453                                           1453    // dlg116:""; dlg159:""
#define IDC_1455                                           1455    // dlg116:""; dlg159:""
#define IDC_1456                                           1456    // dlg127:""
#define IDC_1457                                           1457    // dlg127:""
#define IDC_1459                                           1459    // dlg127:""
#define IDC_COLOR                                          1460    // dlg187:"Color..."
#define IDC_1461                                           1461    // dlg127:""; dlg226:"Color..."
#define IDC_1462                                           1462    // dlg187:""
#define IDC_1463                                           1463    // dlg127:""; dlg226:""
#define IDC_ALPHA                                          1464    // dlg187:"Alpha..."; dlg226:"Grab..."
#define IDC_1466                                           1466    // dlg187:""
#define IDC_1467                                           1467    // dlg187:""
#define IDC_GRAB_VALUE                                     1468    // dlg187:"Grab Value"
#define IDC_HEIGHT                                         1469    // dlg187:"Height"
#define IDC_RGB                                            1470    // dlg187:"RGB"
#define IDC_RED                                            1471    // dlg187:"Red"
#define IDC_GREEN                                          1472    // dlg187:"Green"
#define IDC_BLUE                                           1473    // dlg187:"Blue"
// (dup diff val 1464) #define IDC_ALPHA                                          1474    // dlg187:"Alpha"
#define IDC_TERRAIN_USES_3D_DISTANCE__GOOD_FOR_CURVY       1475    // dlg159:"Terrain uses 3d distance (good for curvy walls)"
#define IDC_TERRAIN_EMULATES_CURVES__BACKWARDS_COMPA       1476    // dlg159:"Terrain emulates curves (backwards compatibility)"
// (dup diff val 1449) #define IDC_TERRAIN_USES_2D_DISTANCE__GOOD_FOR_GROUN       1477    // dlg116:"Terrain uses 2D distance (good for ground)"
// (dup diff val 1475) #define IDC_TERRAIN_USES_3D_DISTANCE__GOOD_FOR_CURVY       1478    // dlg116:"Terrain uses 3d distance (good for curvy walls)"
// (dup diff val 1476) #define IDC_TERRAIN_EMULATES_CURVES__BACKWARDS_COMPA       1479    // dlg116:"Terrain emulates curves (backwards compatibility)"
#define IDC_1480                                           1480    // dlg127:""
#define IDC_1481                                           1481    // dlg127:""
#define IDC_1482                                           1482    // dlg187:""
#define IDC_1483                                           1483    // dlg187:""
#define IDC_THICK_SELECTION_LINES                          1486    // dlg127:"Thick selection lines"
#define IDC_DONE                                           1489    // dlg116:"Done"
#define IDC_1490                                           1490    // dlg128:"888888"
#define IDC_1491                                           1491    // dlg128:"888888"
#define IDC_1492                                           1492    // dlg128:"888888"
#define IDC_1493                                           1493    // dlg128:"888888"
#define IDC_1494                                           1494    // dlg128:"888888"
#define IDC_1495                                           1495    // dlg128:"888888"
#define IDC_1496                                           1496    // dlg128:"888888"
#define IDC_1497                                           1497    // dlg128:"888888"
#define IDC_1498                                           1498    // dlg128:"888888"
#define IDC_1499                                           1499    // dlg128:"888888"
#define IDC_1500                                           1500    // dlg128:"888888"
#define IDC_1501                                           1501    // dlg128:"888888"
#define IDC_1502                                           1502    // dlg128:"888888"
#define IDC_1503                                           1503    // dlg128:"888888"
#define IDC_1504                                           1504    // dlg128:"888888"
#define IDC_1505                                           1505    // dlg128:"888888"
#define IDC_1506                                           1506    // dlg128:"888888"
#define IDC_1507                                           1507    // dlg128:"888888"
#define IDC_1508                                           1508    // dlg128:"888888"
#define IDC_1509                                           1509    // dlg128:"888888"
#define IDC_1510                                           1510    // dlg128:"888888"
#define IDC_1511                                           1511    // dlg128:"888888"
#define IDC_1512                                           1512    // dlg128:"888888"
#define IDC_1513                                           1513    // dlg128:"888888"
#define IDC_1514                                           1514    // dlg128:"888888"
#define IDC_1515                                           1515    // dlg128:"888888"
#define IDC_1516                                           1516    // dlg128:"888888"
#define IDC_CULL_SKY_ON_CLIP                               1517    // dlg127:"Cull sky on clip"
#define IDC_1518                                           1518    // dlg224:""
#define IDC_UVS                                            1519    // dlg224:"UVs"
#define IDC_QUADS                                          1520    // dlg224:"Quads"
#define IDC_INCHES                                         1521    // dlg224:"Inches"
#define IDC_CENTIMETERS                                    1522    // dlg224:"Centimeters"
#define IDC_RECURSE_INTO_PREFABS                           1525    // dlg147:"Recurse into Prefabs"
// (dup diff val 3) #define IDC_APPLY                                          1526    // dlg226:"Apply"
#define IDC_1527                                           1527    // dlg226:""
#define IDC_1528                                           1528    // dlg226:""
// (dup diff val 1464) #define IDC_ALPHA                                          1529    // dlg226:"Alpha"
// (dup diff val 1460) #define IDC_COLOR                                          1530    // dlg226:"Color"
#define IDC_1533                                           1533    // dlg226:""
#define IDC_1534                                           1534    // dlg226:""
#define IDC_1535                                           1535    // dlg226:""
#define IDC_REAL_TIME                                      1537    // dlg226:"Real Time"
#define IDC_USE_MOUSE_WHEEL_IN_CAMERA_WINDOW               1538    // dlg127:"Use mouse wheel in camera window"
#define IDC_SPAWN_VEHICLE                                  1540    // dlg228:"Spawn Vehicle"
#define IDC_MOVE_VEHICLE                                   1542    // dlg228:"Move Vehicle"
#define IDC_DELETE_VEHICLE                                 1543    // dlg228:"Delete Vehicle"
#define IDC_RIDE_ON_IN_VEHICLE                             1545    // dlg228:"Ride On/In Vehicle"
#define IDC_WALK_WITH_VEHICLE                              1546    // dlg228:"Walk with Vehicle"
#define IDC_SET_TEAM_ALLIES                                1548    // dlg228:"Set Team Allies"
#define IDC_SET_TEAM__AXIS                                 1549    // dlg228:"Set Team: Axis"
#define IDC_DISABLE_MACHINE_GUNS                           1550    // dlg228:"Disable Machine Guns"
#define IDC_ENABLE_MACHINE_GUNS                            1551    // dlg228:"Enable Machine Guns"
#define IDC_VEHICLE_ATTACK_GROUP                           1552    // dlg228:"Vehicle Attack Group"
#define IDC_VEHICLE_FOCUS_FIRE                             1553    // dlg228:"Vehicle Focus Fire"
#define IDC_MAKE_VEHICLE_DETOUR                            1554    // dlg228:"Make Vehicle Detour"
#define IDC_MAKE_VEHICLE_GATE                              1555    // dlg228:"Make Vehicle Gate"
#define IDC_ENABLE_DEATHROLL                               1556    // dlg228:"Enable Deathroll"
#define IDC_DISABLE_DEATHROLL                              1558    // dlg228:"Disable Deathroll"
#define IDC_1559                                           1559    // dlg127:""
#define IDC_1560                                           1560    // dlg116:"88888"; dlg127:""
#define IDC_1561                                           1561    // dlg228:"?"
#define IDC_1562                                           1562    // dlg116:"88888"
#define IDC_1563                                           1563    // dlg228:"?"
#define IDC_1564                                           1564    // dlg229:""
#define IDC_1565                                           1565    // dlg228:"?"
#define IDC_1566                                           1566    // dlg229:""
#define IDC_1567                                           1567    // dlg228:"?"
// (dup diff val 4) #define IDC_ADD                                            1568    // dlg229:"Add..."
#define IDC_1569                                           1569    // dlg228:"?"; dlg229:"Add Selected"
// (dup diff val 4) #define IDC_ADD                                            1570    // dlg229:"Add..."
#define IDC_1571                                           1571    // dlg228:"?"
#define IDC_1572                                           1572    // dlg228:"?"
#define IDC_1574                                           1574    // dlg228:"?"
#define IDC_SHUFFLE                                        1575    // dlg229:"Shuffle"
#define IDC_DELETE                                         1576    // dlg229:"Delete"
#define IDC_1577                                           1577    // dlg228:"?"
// (dup diff val 1576) #define IDC_DELETE                                         1578    // dlg229:"Delete"
#define IDC_1579                                           1579    // dlg228:"?"; dlg229:"Add Selected"
#define IDC_COPY_TO_SOURCE                                 1580    // dlg229:"Copy to Source"
#define IDC_COPY_TO_DEST                                   1581    // dlg229:"Copy to Dest"
#define IDC_1582                                           1582    // dlg228:"?"
#define IDC_1584                                           1584    // dlg228:"?"
#define IDC_ENABLE_MAIN_TURRET                             1586    // dlg228:"Enable Main Turret"
#define IDC_DISABLE_MAIN_TURRET                            1587    // dlg228:"Disable Main Turret"
#define IDC_1588                                           1588    // dlg228:"?"
#define IDC_ENABLE_BADPLACES                               1589    // dlg228:"Enable Badplaces"
#define IDC_DISABLE_BADPLACES                              1590    // dlg228:"Disable Badplaces"
#define IDC_1591                                           1591    // dlg228:"?"
#define IDC_ENABLE_AVOID_VEHICLES                          1592    // dlg228:"Enable Avoid Vehicles"
#define IDC_DISABLE_AVOID_VEHICLES                         1593    // dlg228:"Disable Avoid Vehicles"
#define IDC_1594                                           1594    // dlg228:"?"
#define IDC_SET_HEALTH                                     1596    // dlg228:"Set Health"
#define IDC_1597                                           1597    // dlg228:""
#define IDC_RESET_DEFAULT                                  1598    // dlg228:"Reset Default"
#define IDC_1599                                           1599    // dlg228:"?"
#define IDC_1600                                           1600    // dlg228:""
#define IDC_1601                                           1601    // dlg228:"?"
#define IDC_SET_ACCURACY                                   1602    // dlg228:"Set Accuracy"
#define IDC_1603                                           1603    // dlg228:""
// (dup diff val 1598) #define IDC_RESET_DEFAULT                                  1604    // dlg228:"Reset Default"
#define IDC_VEHICLE_ATTACK_ORIGINS                         1605    // dlg228:"Vehicle Attack Origins"
#define IDC_REFRESH                                        1606    // dlg230:"Refresh"; dlg251:"Set"
#define IDC_DISABLE_TURRET_ATTACK_AI                       1607    // dlg228:"Disable Turret Attack AI"; dlg251:"Clear"
#define IDC_1608                                           1608    // dlg228:"?"; dlg251:"Set"
#define IDC_ENABLE_TURRET_ATTACK_AI                        1609    // dlg228:"Enable Turret Attack AI"; dlg251:"Clear"
#define IDC_1610                                           1610    // dlg228:"?"; dlg251:"Set"
#define IDC_1611                                           1611    // dlg228:""; dlg251:"Clear"
#define IDC_SET_CRASH_TYPE                                 1612    // dlg228:"Set Crash Type"
// (dup diff val 6) #define IDC_REMOVE                                         1613    // dlg228:"Remove"; dlg251:"Set"
#define IDC_1614                                           1614    // dlg228:"?"
#define IDC_SET_SPEED                                      1615    // dlg228:"Set Speed"; dlg251:"Clear"
#define IDC_DELETE_KEY                                     1616    // dlg228:"Delete Key"
#define IDC_1617                                           1617    // dlg228:""
#define IDC_1618                                           1618    // dlg228:"?"
#define IDC_SET_LOOKAHEAD                                  1619    // dlg228:"Set Lookahead"
// (dup diff val 1616) #define IDC_DELETE_KEY                                     1620    // dlg228:"Delete Key"
#define IDC_1621                                           1621    // dlg228:"?"
#define IDC_1622                                           1622    // dlg228:""
#define IDC_1626                                           1626    // dlg180:""
#define IDC_1627                                           1627    // dlg180:""
#define IDC_1628                                           1628    // dlg180:""
#define IDC_1629                                           1629    // dlg180:""
#define IDC_1631                                           1631    // dlg217:""
#define IDC_1632                                           1632    // dlg230:""
#define IDC_1635                                           1635    // dlg217:""
#define IDC_1636                                           1636    // dlg217:""
#define IDC_1639                                           1639    // dlg217:""
#define IDC_1652                                           1652    // dlg217:"#240"
#define IDC_1653                                           1653    // dlg217:"#241"
#define IDC_1654                                           1654    // dlg217:"#246"
#define IDC_1655                                           1655    // dlg217:"#243"
#define IDC_1656                                           1656    // dlg217:"#242"
#define IDC_1657                                           1657    // dlg217:"#245"
#define IDC_1658                                           1658    // dlg217:"#244"
#define IDC_1661                                           1661    // dlg217:""
#define IDC_1662                                           1662    // dlg217:""
#define IDC_1663                                           1663    // dlg217:""
#define IDC_1664                                           1664    // dlg217:""
// (dup diff val 1006) #define IDC_N                                              1665    // dlg217:"n"
#define IDC_1666                                           1666    // dlg217:""
#define IDC_1667                                           1667    // dlg217:""
// (dup diff val 1006) #define IDC_N                                              1668    // dlg217:"n"
// (dup diff val 1006) #define IDC_N                                              1670    // dlg217:"n"
#define IDC_1671                                           1671    // dlg217:""
#define IDC_FAST_2D_VIEW_DRAGGING                          1672    // dlg127:"Fast 2d view dragging"
#define IDC_1673                                           1673    // dlg127:"..."; dlg251:"Help"
#define IDC_DETACHED_WINDOWS                               1674    // dlg127:"Detached Windows"
#define IDC_STATIC                                         1676    // dlg249:"Static"
// (dup diff val 1676) #define IDC_STATIC                                         1677    // dlg249:"Static"
// (dup diff val 1676) #define IDC_STATIC                                         1678    // dlg249:"Static"
// (dup diff val 1676) #define IDC_STATIC                                         1679    // dlg249:"Static"
// (dup diff val 1676) #define IDC_STATIC                                         1680    // dlg249:"Static"
// (dup diff val 1676) #define IDC_STATIC                                         1681    // dlg249:"Static"
// (dup diff val 1676) #define IDC_STATIC                                         1682    // dlg249:"Static"
// (dup diff val 1676) #define IDC_STATIC                                         1683    // dlg249:"Static"
#define IDC_REAPPLY_DEFAULT_MAPPING                        1684    // dlg147:"Reapply default mapping"
#define IDC_1685                                           1685    // dlg127:""
#define IDC_TRANSPARENT_BACKGROUND                         1687    // dlg127:"Transparent background"
#define IDC_1690                                           1690    // dlg251:""
#define IDC_1693                                           1693    // dlg251:""
#define IDC_1694                                           1694    // dlg251:""
#define IDC_1695                                           1695    // dlg251:"..."
#define IDC_1696                                           1696    // dlg251:""
#define IDC_MISC_MODEL                                     1697    // dlg229:"misc_model"; dlg251:"..."
#define IDC_DYN_MODEL                                      1698    // dlg229:"dyn_model"; dlg251:"Set"
#define IDC_MISC_PREFAB                                    1699    // dlg229:"misc_prefab"; dlg251:"Clear"
#define IDC_1700                                           1700    // dlg127:""
#define IDC_1701                                           1701    // dlg251:""
#define IDC_1703                                           1703    // dlg251:"..."
#define IDC_HELP_CMD                                       57670   // dlg30721:"&Help" (renamed: IDC_HELP clashes with winuser.h MAKEINTRESOURCE)
#define IDC_CLOSE                                          58112   // dlg30723:"&Close"
#define IDC_58113                                          58113   // dlg30723:""
#define IDC_NEXT_PAGE                                      58114   // dlg30723:"&Next Page"
#define IDC_PRE_V_PAGE                                     58115   // dlg30723:"Pre&v Page"
#define IDC_PRINT                                          58116   // dlg30723:"&Print..."
#define IDC_ZOOM__IN                                       58117   // dlg30723:"Zoom &In"
#define IDC_ZOOM__OUT                                      58118   // dlg30723:"Zoom &Out"
#define IDC_ENTITY_NUMBER                                  4294967295  // dlg110:"Entity number"; dlg110:"Brush number"; dlg113:"Sides:"

// ── Menu / Accelerator Command IDs ──────────────────────────────────────────
#define ID_CMD_100                                         100
#define ID_CMD_101                                         101
#define ID_CMD_102                                         102
#define ID_CMD_103                                         103
#define ID_CMD_104                                         104
#define ID_CMD_105                                         105
#define ID_CMD_106                                         106
#define ID_CMD_107                                         107
#define ID_CMD_108                                         108
#define ID_CMD_109                                         109
#define ID_CMD_110                                         110
#define ID_CMD_111                                         111
#define ID_CMD_112                                         112
#define ID_CMD_113                                         113
#define ID_CMD_114                                         114
#define ID_CMD_115                                         115
#define ID_CMD_116                                         116
#define ID_CMD_117                                         117
#define ID_CMD_118                                         118
#define ID_CMD_119                                         119
#define ID_CMD_120                                         120
#define ID_CMD_121                                         121
#define ID_CMD_122                                         122
#define ID_CMD_128                                         128
#define ID_CMD_129                                         129
#define ID_CMD_136                                         136
#define ID_CMD_144                                         144
#define ID_CMD_189                                         189
#define ID_CMD_195                                         195
#define ID_CMD_196                                         196
#define ID_CMD_197                                         197
#define ID_CMD_200                                         200
#define ID_CMD_202                                         202
#define ID_CMD_206                                         206
#define ID_CMD_209                                         209
#define ID_CMD_210                                         210
#define ID_CMD_211                                         211
#define ID_CMD_212                                         212
#define ID_CMD_213                                         213

